# Generated by Django 4.2.6 on 2023-10-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_video_name_remove_video_videofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
